# General website settings

title: tinychameleon
url: https://tinychameleon.com
permalink: /:title/
timezone: America/Vancouver
date_format: "%B %e, %Y"
title_suffix: Stephan Tarulli


# Build command settings

incremental: true
strict_front_matter: true

exclude:
  - _bin
  - _tmp
  - .env
  - .envrc
  - .gitignore
  - .ruby-version
  - cache.filter
  - infra.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - todo_list


# Plugin settings

asciidoc: {}
asciidoctor:
  attributes:
    - page-liquid=true@
    - icons=font

feed:
  excerpt_only: true
